[ColorScheme]
active_colors=
disabled_colors=#c1c9b9, #1e251a, #282f24, #1e251a, #181e14, #181e14, #c1c9b9, #c1c9b9, #c1c9b9, #1e251a, #1e251a,
inactive_colors=#c1c9b9, #0f150b, #282f24, #1e251a, #181e14, #181e14, #c1c9b9, #c1c9b9, #c1c9b9, #0f150b, #0f150b,

[ColorEffects:Disabled]
Color=#c1c9b9
ColorAmount=0
ColorEffect=0
ContrastAmount=0.65
ContrastEffect=1
IntensityAmount=0.1
IntensityEffect=2

[ColorEffects:Inactive]
ChangeSelectionColor=true
Color=#c1c9b9
ColorAmount=0.025
ColorEffect=2
ContrastAmount=0.1
ContrastEffect=2
Enable=false
IntensityAmount=0
IntensityEffect=0

[Colors:Button]
BackgroundAlternate=30,37,26
BackgroundNormal=30,37,26
DecorationFocus=75,227,0
DecorationHover=75,227,0
ForegroundActive=75,227,0
ForegroundInactive=200,200,200
ForegroundLink=148,212,184
ForegroundNegative=255,180,171
ForegroundNeutral=171,207,176
ForegroundNormal=255,255,255
ForegroundPositive=75,227,0
ForegroundVisited=148,212,184

[Colors:Complementary]
BackgroundAlternate=30,37,26
BackgroundNormal=15,21,11
DecorationFocus=75,227,0
DecorationHover=75,227,0
ForegroundActive=75,227,0
ForegroundInactive=200,200,200
ForegroundLink=148,212,184
ForegroundNegative=255,180,171
ForegroundNeutral=171,207,176
ForegroundNormal=255,255,255
ForegroundPositive=75,227,0
ForegroundVisited=148,212,184

[Colors:Header]
BackgroundAlternate=30,37,26
BackgroundNormal=15,21,11
DecorationFocus=75,227,0
DecorationHover=75,227,0
ForegroundActive=75,227,0
ForegroundInactive=200,200,200
ForegroundLink=148,212,184
ForegroundNegative=255,180,171
ForegroundNeutral=171,207,176
ForegroundNormal=255,255,255
ForegroundPositive=75,227,0
ForegroundVisited=148,212,184

[Colors:Header][Inactive]
BackgroundAlternate=30,37,26
BackgroundNormal=15,21,11
DecorationFocus=75,227,0
DecorationHover=75,227,0
ForegroundActive=75,227,0
ForegroundInactive=200,200,200
ForegroundLink=148,212,184
ForegroundNegative=255,180,171
ForegroundNeutral=171,207,176
ForegroundNormal=255,255,255
ForegroundPositive=75,227,0
ForegroundVisited=148,212,184

[Colors:Selection]
BackgroundAlternate=75,227,0
BackgroundNormal=75,227,0
DecorationFocus=75,227,0
DecorationHover=75,227,0
ForegroundActive=9,47,0
ForegroundInactive=9,47,0
ForegroundLink=9,47,0
ForegroundNegative=255,180,171
ForegroundNeutral=9,47,0
ForegroundNormal=9,47,0
ForegroundPositive=9,47,0
ForegroundVisited=9,47,0

[Colors:Tooltip]
BackgroundAlternate=40,47,36
BackgroundNormal=40,47,36
DecorationFocus=75,227,0
DecorationHover=75,227,0
ForegroundActive=75,227,0
ForegroundInactive=200,200,200
ForegroundLink=148,212,184
ForegroundNegative=255,180,171
ForegroundNeutral=171,207,176
ForegroundNormal=255,255,255
ForegroundPositive=75,227,0
ForegroundVisited=148,212,184

[Colors:View]
BackgroundAlternate=24,30,20
BackgroundNormal=15,21,11
DecorationFocus=75,227,0
DecorationHover=75,227,0
ForegroundActive=75,227,0
ForegroundInactive=200,200,200
ForegroundLink=148,212,184
ForegroundNegative=255,180,171
ForegroundNeutral=171,207,176
ForegroundNormal=255,255,255
ForegroundPositive=75,227,0
ForegroundVisited=148,212,184

[Colors:Window]
BackgroundAlternate=30,37,26
BackgroundNormal=15,21,11
DecorationFocus=75,227,0
DecorationHover=75,227,0
ForegroundActive=75,227,0
ForegroundInactive=200,200,200
ForegroundLink=148,212,184
ForegroundNegative=255,180,171
ForegroundNeutral=171,207,176
ForegroundNormal=255,255,255
ForegroundPositive=75,227,0
ForegroundVisited=148,212,184

[WM]
activeBackground=15,21,11
activeBlend=255,255,255
activeForeground=255,255,255
inactiveBackground=15,21,11
inactiveBlend=193,201,185
inactiveForeground=193,201,185
