# Mathias.conf Theme #
background            {{colors.background.default.hex}}
foreground            {{colors.on_background.default.hex}}
cursor                {{colors.primary.default.hex}}
selection_background  {{colors.surface_variant.default.hex}}
color0                {{colors.surface.default.hex}}
color8                {{colors.surface_variant.default.hex}}
color1                {{colors.error.default.hex}}
color9                {{colors.error_container.default.hex}}
color2                {{colors.tertiary.default.hex}}
color10               {{colors.tertiary_container.default.hex}}
color3                {{colors.secondary.default.hex}}
color11               {{colors.secondary_container.default.hex}}
color4                {{colors.primary.default.hex}}
color12               {{colors.primary_container.default.hex}}
color5                {{colors.tertiary_fixed_dim.default.hex}}
color13               {{colors.on_secondary_fixed_variant.default.hex}}
color6                {{colors.secondary_fixed_dim.default.hex}}
color14               {{colors.on_tertiary_fixed_variant.default.hex}}
color7                {{colors.on_surface.default.hex}}
color15               {{colors.on_surface_variant.default.hex}}
selection_foreground  {{colors.on_surface_variant.default.hex}}
# Mathias.conf Theme END#

confirm_os_window_close 0

# BEGIN_KITTY_FONTS
font_family      family="3270 Nerd Font Mono"
bold_font        auto
italic_font      auto
bold_italic_font auto
# END_KITTY_FONTS

shell zsh
shell_integration disabled

cursor_shape beam

url_style curly

window_padding_width 15

cursor_blink_interval 620

background_opacity 0.6205
scrollbar_handle_opacity 0.06205
scrollbar_track_opacity 0.06205
scrollbar_track_hover_opacity 0.06205

sync_to_monitor no

